DROP TABLE IF EXISTS "novidade";
DROP TABLE IF EXISTS "tipo_novidade";
DROP TABLE IF EXISTS "empenho";
DROP TABLE IF EXISTS "alteracoes_contrato";
DROP MATERIALIZED VIEW IF EXISTS item_search;
DROP TABLE IF EXISTS "item_contrato";
DROP TABLE IF EXISTS "contrato";
DROP TABLE IF EXISTS "socios";
DROP TABLE IF EXISTS "cnae_secundario";
DROP TABLE IF EXISTS "dados_cadastrais";
DROP TABLE IF EXISTS "cnae";
DROP TABLE IF EXISTS "fornecedor";
DROP TABLE IF EXISTS "licitante";
DROP TABLE IF EXISTS "item";
DROP TABLE IF EXISTS "documento_licitacao";
DROP TABLE IF EXISTS "licitacao";
DROP TABLE IF EXISTS "orgao";