version: '3.5'

services:   

  rbase:
    build: 
      context: code/
    container_name: r-container
    restart: always
    environment:
      - USER=${USER:-admin}
      - PASSWORD=${PASSWORD:-secret}      
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-tanamesa}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
    volumes:
      - ./code:/app/code
      - ./data:/app/data
    ports:
      - 8787:8787
    networks:
      - proxynet

  feed:
    build:
      context: feed/
    container_name: feed
    image: feed-image
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./feed:/feed
    ports:
      - 7643:7643
    depends_on:
      - postgres
    networks:
      - proxynet

  postgres:
    image: postgres:11.1-alpine
    container_name: postgres-ta-na-mesa
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-tanamesa}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secret}
      - TZ=GMT
    volumes:
      - postgres_data:/var/lib/postgresql/data/    
    ports:
      - 7655:5432
    networks:
      - proxynet

networks:
  proxynet:
    name: ta_na_mesa_network
      
volumes:
  postgres_data:
  