version: '3.5'

services:   

  feed-prod:
    build:
      context: feed/
    container_name: feed-prod
    image: feed-image-prod
    env_file:
      - .env.prod
    volumes:
      - ./data:/data
      - ./feed:/feed
    ports:
      - 7644:7644
    networks:
      - proxynet

networks:
  proxynet:
    name: ta_na_mesa_network
  