DROP TABLE IF EXISTS "empenho";
DROP TABLE IF EXISTS "item_contrato";
DROP TABLE IF EXISTS "contrato";
DROP TABLE IF EXISTS "licitante";
DROP TABLE IF EXISTS "item";
DROP TABLE IF EXISTS "licitacao";
DROP TABLE IF EXISTS "orgao";