DROP TABLE IF EXISTS item_contrato;

CREATE TABLE IF NOT EXISTS "item_contrato" (
    "id_item_contrato" VARCHAR(32),
    "id_contrato" VARCHAR(32),
    "id_orgao" VARCHAR(32),
    "cd_orgao" INTEGER,
    "id_licitacao" VARCHAR(32),
    "id_item_licitacao" VARCHAR(32),
    "nr_lote" INTEGER,
    "nr_licitacao" VARCHAR(20),
    "ano_licitacao" INTEGER,
    "cd_tipo_modalidade" VARCHAR(3),
    "nr_contrato" VARCHAR(40),
    "ano_contrato" INTEGER,
    "tp_instrumento_contrato" VARCHAR(15),
    "nr_item" INTEGER,
    "qt_itens_contrato" REAL,
    "vl_item_contrato" REAL,
    "vl_total_item_contrato" REAL,
    "origem_valor" VARCHAR(10),
    "sigla_estado" VARCHAR(2),
    "id_estado" INTEGER,
    "dt_inicio_vigencia" DATE,
    "ds_item" TEXT,
    "sg_unidade_medida" VARCHAR(15),
    "categoria" INTEGER,
    "language" VARCHAR(15),
    "ds_1" TEXT,
    "ds_2" TEXT,
    "ds_3" TEXT,
    "servico" BOOLEAN,
    PRIMARY KEY ("id_item_contrato"),
    CONSTRAINT item_contrato_key UNIQUE (id_orgao, ano_licitacao, nr_licitacao, cd_tipo_modalidade, nr_contrato, ano_contrato, 
    tp_instrumento_contrato, nr_lote, nr_item),
    FOREIGN KEY ("id_contrato") REFERENCES contrato("id_contrato") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY ("id_orgao") REFERENCES orgao("id_orgao") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY ("id_licitacao") REFERENCES licitacao("id_licitacao") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY ("id_item_licitacao") REFERENCES item("id_item") ON DELETE CASCADE ON UPDATE CASCADE
);
