DROP TABLE IF EXISTS empenho;

CREATE TABLE IF NOT EXISTS "empenho" (
    "id_empenho" BIGINT, 
    "id_licitacao" VARCHAR(32),
    "id_orgao" INTEGER,
    "ano_recebimento" INTEGER,
    "mes_recebimento" INTEGER,
    "ano_empenho" INTEGER,
    "ano_operacao" INTEGER,
    "dt_empenho" DATE,
    "dt_operacao" DATE,
    "nr_empenho" VARCHAR(40),
    "cd_funcao" INTEGER,
    "ds_funcao" VARCHAR(240),
    "cd_subfuncao" INTEGER,
    "ds_subfuncao" VARCHAR(240),
    "cd_programa" INTEGER,
    "ds_programa" VARCHAR(240),
    "cd_projeto" VARCHAR(240),
    "nm_projeto" VARCHAR(240),
    "cd_recurso" VARCHAR(240),
    "nm_recurso" VARCHAR(240),
    "cd_credor" VARCHAR(240),
    "nm_credor" VARCHAR(240),
    "cnpj_cpf" VARCHAR(14),
    "vl_empenho" REAL,
    "nr_liquidacao" VARCHAR(40),
    "vl_liquidacao" REAL,
    "nr_pagamento" VARCHAR(40),
    "vl_pagamento" REAL,
    "ano_licitacao" INTEGER,
    "nr_licitacao" VARCHAR(20),
    "cd_tipo_modalidade" VARCHAR(240),
    "ano_contrato" INTEGER,
    "nr_contrato" VARCHAR(40),
    FOREIGN KEY ("id_licitacao") REFERENCES licitacao("id_licitacao") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY ("id_orgao") REFERENCES orgao("id_orgao") ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY("id_empenho")
);
