DROP TABLE IF EXISTS contrato;

CREATE TABLE IF NOT EXISTS "contrato" ( 
    "id_contrato" INTEGER,
    "id_licitacao" INTEGER,
    "id_orgao" INTEGER,
    "nr_contrato" INTEGER,
    "ano_contrato" INTEGER,
    "nm_orgao" VARCHAR(240),
    "nr_licitacao" VARCHAR(20),
    "ano_licitacao" INTEGER,
    "cd_tipo_modalidade" VARCHAR(3),
    "tp_instrumento_contrato" VARCHAR(1),
    "nr_processo" VARCHAR(20),
    "ano_processo" INTEGER,
    "tp_documento_contratado" VARCHAR(1),
    "nr_documento_contratado" VARCHAR(14),
    "dt_inicio_vigencia" DATE,
    "dt_final_vigencia" DATE,
    "vl_contrato" REAL,
    "contrato_possui_garantia" VARCHAR(1),
    "vigencia_original_do_contrato" INTEGER,
    "descricao_objeto_contrato" VARCHAR(500),
    "justificativa_contratacao" VARCHAR(300),
    "obs_contrato" VARCHAR(500),
    "tipo_instrumento_contrato" VARCHAR(50),
    PRIMARY KEY("id_contrato"),
    CONSTRAINT contrato_key UNIQUE (id_orgao, nr_licitacao, ano_licitacao, cd_tipo_modalidade, nr_contrato, ano_contrato, tp_instrumento_contrato),
    FOREIGN KEY("id_orgao") REFERENCES orgao("id_orgao") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY("id_licitacao") REFERENCES licitacao("id_licitacao") ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY("nr_documento_contratado") REFERENCES fornecedor("nr_documento") ON DELETE CASCADE ON UPDATE CASCADE
);