---
title: "A merenda de Caxias do Sul em 2018"
output: 
  html_document:
    css: styles.css
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.cap = '',
  fig.align = 'center',
  fig.width = 10,
  fig.height = 8
)
```

```{r}
options(scipen = 999)
library(tidyverse)
library(hrbrthemes)
library(ggbeeswarm)
library(lubridate)
library(ggchicklet)
library(magrittr)
library(GGally)
library(stringr)
theme_set(theme_minimal())

source(here::here("code/licitacoes/processa_licitacoes.R"))
source(here::here("code/licitacoes/processa_licitantes.R"))
source(here::here("code/licitacoes/processa_pessoas.R"))
```

```{r}
filtra_licitacoes <- function(licitacoes, palavra_chave) {
  
  licitacoes_filtradas <- licitacoes %>%  
    filter(grepl(palavra_chave, tolower(DS_OBJETO)), CD_TIPO_FASE_ATUAL == "ADH")  %>%
    select(id, CD_ORGAO, NM_ORGAO, NR_LICITACAO, 
           ANO_LICITACAO, CD_TIPO_MODALIDADE, 
           DS_OBJETO, VL_LICITACAO, DT_ABERTURA, 
           DT_HOMOLOGACAO, DT_ADJUDICACAO) %>% 
    mutate(DT_ADJUDICACAO = as.Date(DT_ADJUDICACAO),
           DT_ABERTURA = as.Date(DT_ABERTURA))
  
}
```

```{r}
anos <- c(2018)

licitacoes <- processa_licitacoes(anos)

licitacoes_cpp <- licitacoes %>% 
  filter(CD_TIPO_MODALIDADE == "CPP")

licitacoes_cx <- licitacoes %>% 
  mutate(id = paste0(CD_ORGAO, CD_TIPO_MODALIDADE, NR_LICITACAO, ANO_LICITACAO)) %>% 
  filter(NM_ORGAO == 'PM DE CAXIAS DO SUL')

merenda <- licitacoes_cx %>%  filtra_licitacoes(palavra_chave = "merenda")

cpp <- licitacoes_cx %>%  
  filter(CD_TIPO_MODALIDADE == "CPP", CD_TIPO_FASE_ATUAL == "ADH")  %>%
  select(id, CD_ORGAO, NM_ORGAO, NR_LICITACAO, 
         ANO_LICITACAO, CD_TIPO_MODALIDADE, 
         DS_OBJETO, VL_LICITACAO, DT_ABERTURA, 
         DT_HOMOLOGACAO, DT_ADJUDICACAO) %>% 
  mutate(DT_ADJUDICACAO = as.Date(DT_ADJUDICACAO),
         DT_ABERTURA = as.Date(DT_ABERTURA))

itens_cx <- read_csv("data/licitacoes/2018/item.csv") %>% filter(CD_ORGAO == 45000)

itens_cx_cpp <- itens_cx %>% filter(CD_TIPO_MODALIDADE == "CPP") %>% 
  mutate(id = paste0(CD_ORGAO, CD_TIPO_MODALIDADE, NR_LICITACAO, ANO_LICITACAO))

contratos_cx <- read_csv("data/contratos/2018/contrato.csv") %>% filter(CD_ORGAO == 45000)
alteracao_cx <- read_csv("data/contratos/2018/alteracao.csv") %>% filter(CD_ORGAO == 45000) 

contratos_cx_cpp <- contratos_cx %>% filter(CD_TIPO_MODALIDADE == "CPP") %>% 
  mutate(id = paste0(CD_ORGAO, CD_TIPO_MODALIDADE, NR_LICITACAO, ANO_LICITACAO))
alteracao_cx_cpp <- alteracao_cx %>% filter(CD_TIPO_MODALIDADE == "CPP") %>% 
  mutate(id = paste0(CD_ORGAO, CD_TIPO_MODALIDADE, NR_LICITACAO, ANO_LICITACAO))

empenhos_cx <- read_csv("data/empenhos/2018/caxias_do_sul.csv") %>% filter(cd_orgao == 45000)

empenhos_cx_cpp <- empenhos_cx %>% filter(mod_licitacao == "CPP") %>% 
  mutate(id = paste0(cd_orgao, mod_licitacao, nr_licitacao, ano_licitacao))

censo_escolar_cx <- read_csv("data/censo_escolar/censo_escolar_2018.csv")
```

Quantidade
```{r}
licitacoes_qtd <- licitacoes_cpp %>% 
  group_by(CD_ORGAO, NM_ORGAO) %>% 
  summarise(num_licitacoes = n())

licitacoes_qtd %>% 
  ggplot(aes(x = num_licitacoes)) + 
  geom_histogram() +
  geom_label(aes(x=3, y=120, label="Caxias do Sul está aqui"), color="#69b3a2")
```

Tempo

O município de Caxias do Sul possui duas licitações da modalidade CPP e o intervalo de tempo entre a data de adjudicação e homologação foi de zero dias.

Valor
```{r}
licitacoes_cpp %>% 
  ggplot(aes(x = "", 
             y = VL_LICITACAO, 
             colour=if_else(NM_ORGAO == "PM DE CAXIAS DO SUL", "red", "black"),
             alpha = .8)) +
  ggbeeswarm::geom_quasirandom()
  
```


Itens
```{r}
itens_cx_cpp_tb <- itens_cx_cpp %>% 
  select(DS_ITEM, QT_ITENS, SG_UNIDADE_MEDIDA, VL_UNITARIO_ESTIMADO, VL_TOTAL_ESTIMADO) %>% 
  mutate(produto = strsplit(DS_ITEM, ":")) %>% 
  mutate(nome_item = unlist(lapply(produto, "[[", 1)))
```


```{r echo=TRUE, warning=FALSE}
empenhos_por_mes <- empenhos_cx_cpp %>% 
  mutate(mes_empenho = lubridate::month(lubridate::ymd(dt_empenho))) %>% 
  group_by(mes_empenho) %>% 
  summarise(qtd_empenhos = n())

mes_empenho = c(2, 5, 6, 9, 10)
qtd_empenhos = c(0, 0, 0, 0, 0)

meses_vazios = data.frame(mes_empenho, qtd_empenhos)

empenhos_por_mes %<>% bind_rows(meses_vazios) 

empenhos_por_mes %>% 
  ggplot(aes(x = as.factor(mes_empenho), y = qtd_empenhos)) +
  geom_chicklet(width = .7, radius = grid::unit(5, "pt"), fill = "steelblue") +
  labs(x = "Mês do ano",
       y = "Número de empenhos",
       title = "Empenhos feitos por mês em 2018") +
  theme_ipsum_rc()
```


```{r}
origem_verba <- empenhos_cx_cpp %>% 
  group_by(nm_recurso = if_else(grepl("pnae", tolower(nm_recurso)), "PNAE", "Outros")) %>% 
  summarise(numero_empenhos = n())

origem_verba %>% 
  ggplot(aes(x = nm_recurso, y = numero_empenhos)) +
  geom_chicklet(width = .3, radius = grid::unit(5, "pt"), fill = "steelblue") +
  labs(x = "Recurso",
       y = "Número de empenhos",
       title = "Origem da verba dos empenhos") +
  theme_ipsum_rc(grid="Y")

```

```{r}
uso_verba <- empenhos_cx %>% 
  filter(grepl("pnae", tolower(nm_recurso))) %>% 
  select(mod_licitacao, ds_funcao, ds_subfuncao) %>% 
  group_by(mod_licitacao) %>% 
  summarise(qtd_empenhos = n())

uso_verba %>% 
  ggplot(aes(x = reorder(mod_licitacao, qtd_empenhos), y = qtd_empenhos)) +
  geom_chicklet(width = .3, radius = grid::unit(5, "pt"), fill = "steelblue") +
  labs(x = "Modalidade da licitação",
       y = "Número de empenhos",
       title = "Número de empenhos por \nmodalidade de licitação") +
  theme_ipsum_rc(grid="Y")

```


```{r}

valores_empenhos <- empenhos_cx_cpp %>% 
  select(nr_empenho, vl_empenho, vl_liquidacao, vl_pagamento)
valores_empenhos[is.na(valores_empenhos)] <- 0
valores_empenhos <- valores_empenhos %>% group_by(nr_empenho) %>% 
  summarise(Empenho = sum(vl_empenho),
            Liquidação = sum(vl_liquidacao),
            Pagamento = sum(vl_pagamento))

ggparcoord(valores_empenhos,
    columns = 2:4, 
    showPoints = TRUE, 
        scale="globalminmax",

    title = "Original",
    alphaLines = 0.3
    ) + 
  theme_ipsum_rc()
```


```{r}

nmr_estudantes <- censo_escolar_cx %>% 
  filter(tipo_educacao == "regular") %>% 
  group_by(municipio) %>% 
  summarise(qtd_estudantes = sum(creche_parcial, creche_integral, pre_escola_parcial,
                                 pre_escola_integral, fundamental_inicial_parcial,
                                 fundamental_inicial_integral, fundamental_final_parcial,
                                 fundamental_final_integral, medio_parcial, medio_integral,
                                 eja_fundamental, eja_medio))

gasto_licitacoes <- licitacoes_cpp %>% 
  select(NM_ORGAO , VL_LICITACAO) %>% 
  mutate(municipio = str_remove(NM_ORGAO, "PM DE ")) %>% 
  group_by(municipio) %>% 
  summarise(media_gasto = mean(VL_LICITACAO)) %>% 
  select(municipio, media_gasto) %>% inner_join(nmr_estudantes)

ggplot(gasto_licitacoes, aes(x=qtd_estudantes, y=media_gasto, color=if_else(municipio == "CAXIAS DO SUL", "red", "blue"))) +
  geom_point() +
  hrbrthemes::theme_ipsum_rc(grid=FALSE) + 
  labs(
  x = "Número de alunos", y = "Gasto com licitações CPP", fill = NULL,
  title = ""
  ) +
  theme(legend.title = element_blank()) 

```


