TABELA_LICITACAO <- 1
TABELA_LICITANTE <- 2
TABELA_ITEM <- 3
TABELA_CONTRATO <- 4
TABELA_ALTERACOES_CONTRATO <- 5
L_ID <- "id_licitacao"
I_ID <- "id_item"
CONTRATO_ID <- "id_contrato"
LICITANTE_ID <- "id_licitante"
ALTERACOES_CONTRATO_ID <- "id_alteracoes_contrato" 
